#ifndef GUARD_CONSTANTS_LAYOUTS_H
#define GUARD_CONSTANTS_LAYOUTS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/layouts/layouts.json
//

#define LAYOUT_MYSTERIOUS_CAVE_B1F_1R 1
#define LAYOUT_MYSTERIOUS_CAVE_B1F_2R 2
#define LAYOUT_THE_ENTRANCE 3
#define LAYOUT_MYSTERIOUS_CAVE_1F_1R 4
#define LAYOUT_MYSTERIOUS_CAVE_B1F_3R 5

#endif // GUARD_CONSTANTS_LAYOUTS_H
